# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Loom < Formula
  desc "Capture, ship, summarize, and explore agent session transcripts"
  homepage "https://github.com/EnderRealm/loom"
  version "1.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/EnderRealm/loom/releases/download/v1.1.1/loom_1.1.1_darwin_amd64.tar.gz"
      sha256 "dcad587a8ce8548716c8f875a267c3dbc687651584d319d89c083f9096165570"

      define_method(:install) do
        bin.install "loom"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/EnderRealm/loom/releases/download/v1.1.1/loom_1.1.1_darwin_arm64.tar.gz"
      sha256 "5ad7190630b72e0dd2b8f92a69d698c500b0daf93e9a6c9309abb358cf2a7a0a"

      define_method(:install) do
        bin.install "loom"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/EnderRealm/loom/releases/download/v1.1.1/loom_1.1.1_linux_amd64.tar.gz"
      sha256 "bb86db358219f49760f47dd50a1ce7d745ec507f75ebe30dbf9ba37feb3ac700"
      define_method(:install) do
        bin.install "loom"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/EnderRealm/loom/releases/download/v1.1.1/loom_1.1.1_linux_arm64.tar.gz"
      sha256 "c59d28f36a1420703e6e23ec75c24d72e665f6e7b3ac0072d2f3f2574abb46be"
      define_method(:install) do
        bin.install "loom"
      end
    end
  end

  test do
    assert_match "Usage: loom", shell_output("#{bin}/loom --help")
  end
end
