# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ticket < Formula
  desc "Markdown-based ticket management CLI"
  homepage "https://github.com/EnderRealm/ticket"
  version "2.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/EnderRealm/ticket/releases/download/v2.1.1/ticket_2.1.1_darwin_amd64.tar.gz"
      sha256 "0655138438d58af72295be8d6cde9207133ada4cf83bf672148eedb8c5d0749c"

      define_method(:install) do
        bin.install "tk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/EnderRealm/ticket/releases/download/v2.1.1/ticket_2.1.1_darwin_arm64.tar.gz"
      sha256 "d49af0ee46193134f42eefd9b4fbe7f732863377f4304adb88983a9b9932d996"

      define_method(:install) do
        bin.install "tk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/EnderRealm/ticket/releases/download/v2.1.1/ticket_2.1.1_linux_amd64.tar.gz"
      sha256 "607cd61faf8c184c1ed0a869599af53f2fa0dbd262deeb73df40dd5ef8fdc221"
      define_method(:install) do
        bin.install "tk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/EnderRealm/ticket/releases/download/v2.1.1/ticket_2.1.1_linux_arm64.tar.gz"
      sha256 "722cdc1d2c3284aea8d4b1bf8238363c27a2071eec3f6f0f524712dd830f4115"
      define_method(:install) do
        bin.install "tk"
      end
    end
  end
end
