# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ticket < Formula
  desc "Markdown-based ticket management CLI"
  homepage "https://github.com/EnderRealm/ticket"
  version "7.2.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/EnderRealm/ticket/releases/download/v7.2.1/ticket_7.2.1_darwin_amd64.tar.gz"
      sha256 "c50a3c834013bd1526c30f6ed0067486eed055531ed8521267115d60022bf998"

      define_method(:install) do
        bin.install "tk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/EnderRealm/ticket/releases/download/v7.2.1/ticket_7.2.1_darwin_arm64.tar.gz"
      sha256 "ae3e8379a9788161c428bb01b56a57905b656f677c4fe07bb58cc756689cf02d"

      define_method(:install) do
        bin.install "tk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/EnderRealm/ticket/releases/download/v7.2.1/ticket_7.2.1_linux_amd64.tar.gz"
      sha256 "b30982034dad298c55ad5fa919c423db1ad59dd3e32dee8106b059f8dac17ccd"
      define_method(:install) do
        bin.install "tk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/EnderRealm/ticket/releases/download/v7.2.1/ticket_7.2.1_linux_arm64.tar.gz"
      sha256 "8c9d3f191363f4af308d80e5edd29f9623fb443c427f86c4ece0a302a1310ca7"
      define_method(:install) do
        bin.install "tk"
      end
    end
  end
end
