# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ticket < Formula
  desc "Markdown-based ticket management CLI"
  homepage "https://github.com/EnderRealm/ticket"
  version "8.5.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/EnderRealm/ticket/releases/download/v8.5.0/ticket_8.5.0_darwin_amd64.tar.gz"
      sha256 "1f68f250ad0420ba16ee1dd2dfe33a5c5f98db8bdc47f8854aa2c0170ba96655"

      define_method(:install) do
        bin.install "tk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/EnderRealm/ticket/releases/download/v8.5.0/ticket_8.5.0_darwin_arm64.tar.gz"
      sha256 "6b8adc0e9696989d7737e7551cb3aac982f2c9fccf15cbe010b1993dcd384692"

      define_method(:install) do
        bin.install "tk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/EnderRealm/ticket/releases/download/v8.5.0/ticket_8.5.0_linux_amd64.tar.gz"
      sha256 "1aef5cd161cbc6420e309fabb74fae61c7dd3d3477cc78bdb9314267bf53463e"
      define_method(:install) do
        bin.install "tk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/EnderRealm/ticket/releases/download/v8.5.0/ticket_8.5.0_linux_arm64.tar.gz"
      sha256 "930003c38617698d5183412236adf3db3e1afb5db649ae56c3e8bf0b1bf2596f"
      define_method(:install) do
        bin.install "tk"
      end
    end
  end
end
