# This file was generated by GoReleaser. DO NOT EDIT.
cask "ticket" do
  name "ticket"
  desc "Markdown-based ticket management CLI"
  homepage "https://github.com/EnderRealm/ticket"
  version "2.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ticket"

  on_macos do
    on_intel do
      url "https://github.com/EnderRealm/ticket/releases/download/v#{version}/ticket_#{version}_darwin_amd64.tar.gz"
      sha256 "263871d1224bf102cb7f5d5e47fce41c7c0124996257b1d2fede08124150f8d7"
    end
    on_arm do
      url "https://github.com/EnderRealm/ticket/releases/download/v#{version}/ticket_#{version}_darwin_arm64.tar.gz"
      sha256 "a485bc1866d33fcc35a223795aeca31a921244b8afc56bc49faff78db07a6586"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/EnderRealm/ticket/releases/download/v#{version}/ticket_#{version}_linux_amd64.tar.gz"
      sha256 "32d05811e075db72b0cba8b3665ada980340bbebcb6d02daa396ff6de6412a96"
    end
    on_arm do
      url "https://github.com/EnderRealm/ticket/releases/download/v#{version}/ticket_#{version}_linux_arm64.tar.gz"
      sha256 "a3cf011aa9779223035b3e9bddfe3ea9efffb66bf3dced795d1dd91ef9d0d8ca"
    end
  end

  # No zap stanza required
end
