# This file was generated by GoReleaser. DO NOT EDIT.
cask "ticket" do
  name "ticket"
  desc "Markdown-based ticket management CLI"
  homepage "https://github.com/EnderRealm/ticket"
  version "2.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ticket"

  on_macos do
    on_intel do
      url "https://github.com/EnderRealm/ticket/releases/download/v#{version}/ticket_#{version}_darwin_amd64.tar.gz"
      sha256 "1271b87d4792625db593e45065db569c1e2b2dd7326dbd08e4e22bba65759552"
    end
    on_arm do
      url "https://github.com/EnderRealm/ticket/releases/download/v#{version}/ticket_#{version}_darwin_arm64.tar.gz"
      sha256 "a3fc257de3d34b015496532cd75a5ecb28f3d6db3f562015e0368e877bcbcb2c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/EnderRealm/ticket/releases/download/v#{version}/ticket_#{version}_linux_amd64.tar.gz"
      sha256 "e813cf5ec06a900f9f598fd920f756d3ffb544fdaf5ad426d9e1c9a26f50b227"
    end
    on_arm do
      url "https://github.com/EnderRealm/ticket/releases/download/v#{version}/ticket_#{version}_linux_arm64.tar.gz"
      sha256 "c1d13ae058ca8a09ad793493ffb899479e70198b501e765044e3f7f6c0a0530b"
    end
  end

  # No zap stanza required
end
